const fs = require('fs');
const pairs = [
  ["text || '加载中 ;", "text || '加载中…';"],
  ["showToast(e.message || '技能执行失败, 'warning');", "showToast(e.message || '技能执行失败', 'warning');"],
  ["'已同意申请，可在智能匹配中邀诀TA 入群' : '已拒绝申诀,", "'已同意申请，可在智能匹配中邀请 TA 入群' : '已拒绝申请',"],
  ["/** 当前匹配模式＀reqs'(选需求找亀 戀'user'(以个人技能找需汀 */", "/** 当前匹配模式：'reqs'(选需求找人) / 'user'(以个人技能找需求) */"],
  ["基于你的技胀${", "基于你的技能 ${"],
  ["showToast(e.message || '邀请失贀, 'warning');", "showToast(e.message || '邀请失败', 'warning');"],
  ["showToast(e.message || '发送失败, 'warning');", "showToast(e.message || '发送失败', 'warning');"],
  ["或发布一条开源需汀", "或发布一条开源需求'"],
  ["'换个筛选条件试诀;", "'换个筛选条件试试';"],
  ["name: '新资満, desc:", "name: '新资源', desc:"],
  ["showToast('名称和角色不能为穀,'warning');", "showToast('名称和角色不能为空','warning');"],
  ["'协作需汀)}</motion>", "'协作需求')}</div>"],
  ["'协作需汀)}</div>", "'协作需求')}</motion>"],
  ["不可恢复　)) return;", "不可恢复。')) return;"],
  ["showToast('请输入群组名秀,'warning');", "showToast('请输入群组名称','warning');"],
  ["showToast('群组已创廀,'success');", "showToast('群组已创建','success');"],
  ["showToast(e.message || '创建工作流失贀", "showToast(e.message || '创建工作流失败"],
  ["showToast(e.message || '创建技能失贀", "showToast(e.message || '创建技能失败"],
  ["showToast(e.message || '工作流执行失贀", "showToast(e.message || '工作流执行失败"],
  ["showToast(e.message || '加载技能市场失贀", "showToast(e.message || '加载技能市场失败"],
  ["showToast(e.message || '保存安装状态失贀", "showToast(e.message || '保存安装状态失败"],
  ["showToast(e.message || '发送失贀", "showToast(e.message || '发送失败"],
  ["console.warn('[skills] 加载已安装技能失贀", "console.warn('[skills] 加载已安装技能失败"],
  ["console.warn('[skills] 加载技能市场失贀", "console.warn('[skills] 加载技能市场失败"],
  ["'验证码已发退", "'验证码已发送"],
  ["'发送失贀", "'发送失败"],
  ["'正在登录 ", "'正在登录…"],
  ["'正在加载数据 ", "'正在加载数据…"],
  ["'上传失败＀", "'上传失败："],
  ["names.join('　)", "names.join('、')"],
  ["'分钟剀", "'分钟前"],
  ["'小时剀", "'小时前"],
  ["'天剀", "'天前"],
  ["'自定义流稀", "'自定义流程"],
  ["'名称和步骤不能为穀", "'名称和步骤不能为空"],
  ["'名称和指令不能为穀", "'名称和指令不能为空"],
  ["?.icon || '⚀", "?.icon || '⚡"],
  ["icon: '✀", "icon: '✨"],
  ["showToast('✀", "showToast('✅"],
  ["已复刀", "已复制"],
  ["定向邀诀", "定向邀请"],
  ["发布到广圀", "发布到广场 ▾"],
  ["⚀技能市", "⚡ 技能市场"],
  ["✀AI 完善", "✨ AI 完善"],
  ["转发到其他对诀", "转发到其他对话"],
  ["空对诀", "空对话"],
  ["新对诀", "新对话"],
  ["我的需汀", "我的需求"],
  ["已发帀", "已发布"],
  ["已匹酀", "已匹配"],
  ["自定义技胀", "自定义技能"],
  ["帮我创建一个技胀", "帮我创建一个技能"],
  ["选择技胀", "选择技能"],
  ["执行 AI 技胀", "执行 AI 技能"],
  ["技能下拉面杀", "技能下拉面板"],
  ["技能面杀", "技能面板"],
  ["工作流模杀", "工作流模板"],
  ["需求广圀", "需求广场"],
  ["组织＀", "组织）"],
  ["API＀", "API）"],
  ["加载＀", "加载）"],
  ["覆盀WORKFLOWS＀", "覆盖 WORKFLOWS）"],
  ["什API", "由 API"],
  ["需汀/", "需求 /"],
  ["失贀", "失败"],
  ["失敗", "失败"],
  ["创廀", "创建"],
  ["名秀", "名称"],
  ["为穀", "为空"],
  ["试诀", "试试"],
  ["申诀", "申请"],
  ["邀诀", "邀请"],
  ["对诀", "对话"],
  ["技胀", "技能"],
  ["文什", "文件"],
  ["流稀", "流程"],
  ["资満", "资源"],
  ["需汀", "需求"],
  ["发帀", "发布"],
  ["匹酀", "匹配"],
  ["登彀", "登录"],
  ["转诀", "转发"],
  ["加诀", "加载"],
  ["保诀", "保存"],
  ["删诀", "删除"],
  ["名诀", "名称"],
  ["创诀", "创建"],
  ["失诀", "失败"],
  ["看眀", "看看"],
  ["覆盀", "覆盖"],
  ["广圀", "广场"],
  ["模杀", "模板"],
  ["面杀", "面板"],
  ["下拉面杀", "下拉面板"],
  ["找亀", "找人"],
  ["戀", "/"],
];

let html = fs.readFileSync('index.html', 'utf8');
for (const [from, to] of pairs) {
  if (from.includes('motion')) continue;
  html = html.split(from).join(to);
}
html = html.split("'协作需求')}</motion>").join("'协作需求')}</div>");
fs.writeFileSync('index.html', html, 'utf8');

const script = html.split('<script>').pop().split('</script>')[0];
try { new Function(script); console.log('JS OK'); }
catch (e) {
  console.log('FAIL', e.message);
  script.split('\n').forEach((line, i) => {
    if ((line.match(/'/g) || []).length % 2 === 1) console.log('odd', i + 1, line.trim().slice(0, 100));
  });
}
